# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sys_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(462, 56)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cpu_persent = QtWidgets.QLabel(Form)
        self.cpu_persent.setObjectName("cpu_persent")
        self.horizontalLayout.addWidget(self.cpu_persent)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.ram_persent = QtWidgets.QLabel(Form)
        self.ram_persent.setObjectName("ram_persent")
        self.horizontalLayout.addWidget(self.ram_persent)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setMaximum(30)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "CPU usage, %: "))
        self.cpu_persent.setText(_translate("Form", "N/A"))
        self.label_3.setText(_translate("Form", "RAM usage, %: "))
        self.ram_persent.setText(_translate("Form", "N/A"))
        self.label_2.setText(_translate("Form", "Delay, s: "))
